import 'package:jamparing_aplikasi/models/product.dart';

final List<Product> products = [
  Product(
    title: "Coffee Brown Sugar",
    image: "assets/images/coffee_brown_sugar.jpg",
    price: 28000,
    category: "Coffee",
    description: "minuman kopi kekinian yang memadukan cita rasa kopi yang kuat dengan manisnya gula aren.",
  ),
  Product(
    title: "Coffee Caramel Latte",
    image: "assets/images/coffee_caramel_latte.jpg",
    price: 32000,
    category: "Coffee",
    description: "erpaduan sempurna kopi espresso dengan rasa karamel manis dan lembut, menciptakan cita rasa yang kaya dan memanjakan.",
  ),
  Product(
    title: "Coffee Latte",
    image: "assets/images/coffee_latte.jpg",
    price: 30000,
    category: "Coffee",
    description: "Kombinasi espresso yang kaya dengan susu lembut, menghasilkan rasa kopi yang halus dan creamy.",
  ),
  Product(
     title: "Ice Americano",
    image: "assets/images/americano.jpg",
    price: 18000,
    category: "Coffee",
    description: "Minuman kopi hitam dingin yang menyegarkan, dengan cita rasa espresso yang kuat dan bold.",
  ),
  Product(
    title: "Cappucino",
    image: "assets/images/cappucino.jpg",
    price: 30000,
    category: "Coffee",
    description: "Kombinasi espresso dengan susu dan foam yang lembut, menghadirkan rasa kopi yang kuat dan creamy dalam setiap tegukan.",
  ),
  Product(
    title: "Espresso",
    image: "assets/images/espresso.jpg",
    price: 15000,
    category: "Coffee",
    description: "Kopi pekat dengan rasa yang intens dan aroma khas, disajikan dalam satu shot untuk kenikmatan kopi yang murni.",
  ),
  Product(
    title: "Macchiato",
    image: "assets/images/macchiato.jpg",
    price: 30000,
    category: "Coffee",
    description: "Shot espresso dengan sedikit foam susu di atasnya, menciptakan keseimbangan rasa kopi yang kuat dan lembut.",
  ),
  Product(
    title: "Vanilla Latte",
    image: "assets/images/vanilla_latte.jpg",
    price: 35000,
    category: "Coffee",
    description: "Perpaduan espresso yang kaya dengan susu lembut dan sentuhan manis vanilla, memberikan cita rasa yang halus dan aromatik.",
  ),
  Product(
    title: "Caramel Macchiato",
    image: "assets/images/caramel_macchiato.jpg",
    price: 40000,
    category: "Coffee",
    description: "Kombinasi espresso yang bold, susu lembut, dan sirup karamel manis, menghasilkan rasa kopi yang kaya dan memanjakan.",
  ),
  Product(
    title: "Hazelnut Cappucino",
    image: "assets/images/hazelnut_cappucino.jpg",
    price: 35000,
    category: "Coffee",
    description: "Paduan espresso yang kaya dengan susu lembut dan aroma hazelnut yang hangat, menciptakan cita rasa kopi yang creamy dan menggoda.",
  ),
  Product(
    title: "Signature Affogato",
    image: "assets/images/signature_affogato.jpg",
    price: 30000,
    category: "Coffee",
    description: "Paduan sempurna antara es krim vanila yang lembut dan shot espresso panas, menciptakan pengalaman rasa manis dan pahit yang menggugah selera.",
  ),
  Product(
    title: "FlatWhite",
    image: "assets/images/flatwhite.jpg",
    price: 25000,
    category: "Coffee",
    description: "Espresso yang kaya dipadu dengan susu steamed lembut tanpa foam tebal, menciptakan rasa kopi yang halus dan seimbang.",
  ),
   Product(
    title: "Mocha",
    image: "assets/images/mocha.jpg",
    price: 30000,
    category: "Coffee",
    description: "Kombinasi espresso yang kuat, susu lembut, dan cokelat manis, menghasilkan rasa kopi yang kaya dengan sentuhan cokelat yang memanjakan.",
  ),
  Product(
    title: "Flavoured Latte",
    image: "assets/images/flavoured_latte.jpg",
    price: 35000,
    category: "Coffee",
    description: "Latte klasik yang dipadukan dengan sirup beraroma, menghadirkan rasa kopi yang lembut dengan sentuhan rasa khas sesuai pilihan.",
  ),
  Product(
    title: "Matcha Latte",
    image: "assets/images/matcha_latte.jpg",
    price: 32000,
    category: "Non Coffee", 
    description: 'Matcha latte adalah minuman campuran bubuk matcha dan susu, dengan rasa lembut, manis, dan sedikit pahit. Minuman ini populer karena kandungan antioksidan matcha.',
    
  ),
  Product(
    title: "Thaitea Latte",
    image: "assets/images/thaitea_latte.jpg",
    price: 25000,
    category: "Non Coffee", 
    description: 'Thai tea latte adalah minuman yang terbuat dari teh hitam Thailand yang diseduh dengan rempah-rempah, kemudian dicampur dengan susu kental manis dan susu cair.',
  ),
  Product(
    title: "Flavoured Milk",
    image: "assets/images/flavoured_milk.jpg",
    price: 25000,
    category: "Non Coffee",
    description: 'Flavoured milk adalah susu yang diberi tambahan rasa, seperti cokelat, stroberi, vanila, atau kopi. Minuman ini memiliki rasa manis dan creamy, membuatnya populer sebagai alternatif susu biasa.',
    
  ),
  Product(
    title: "Iced Salted Caramel ",
    image: "assets/images/ice_salted_caramel.jpg",
    price: 28000,
    category: "Non Coffee", 
    description: 'Iced salted caramel adalah minuman dingin yang terbuat dari campuran kopi atau susu dengan sirup karamel, diberi sedikit garam untuk menciptakan rasa manis dan gurih. ',
    
  ),
  Product(
    title: "Chocolate Mint ",
    image: "assets/images/chocolate_mint.jpg",
    price: 22000,
    category: "Non Coffee", 
    description: 'Chocolate mint adalah perpaduan rasa cokelat manis dan mint segar, menciptakan rasa yang kaya dan menyegarkan.',

  ),
  Product(
    title: "lemon tea",
    image: "assets/images/lemontea.jpg",
    price: 17000,
    category: "Non Coffee", 
    description: 'Lemon tea adalah minuman teh yang diberi perasan lemon, memberikan rasa segar dan sedikit asam.',
  ),
  Product(
    title: "Chocolate",
    image: "assets/images/chocolate.jpg",
    price: 22000,
    category: "Non Coffee", 
    description: 'Chocolate adalah makanan atau minuman yang terbuat dari biji kakao, dengan rasa manis, kaya, dan sering disajikan dalam bentuk batangan, cair, atau panas.',
  ),
  Product(
    title: "Ice Tea",
    image: "assets/images/tea.jpg",
    price: 15000,
    category: "Non Coffee", 
    description: 'Ice tea adalah teh yang disajikan dingin, biasanya manis dan segar, sering ditambah perasan lemon atau buah-buahan.',
  ),
  Product(
    title: "Sparkling Water",
    image: "assets/images/sparkling.jpg",
    price: 12000,
    category: "Non Coffee", 
    description: 'Sparkling water adalah air mineral berkarbonasi yang mengandung gelembung gas karbon dioksida, memberikan sensasi bergelembung dan menyegarkan.',
  ),
  Product(
    title: "Croissant",
    image: "assets/images/croissant.jpg",
    price: 10000,
    category: "Snack", 
    description: 'Croissant adalah roti pastri berlapis tipis, renyah di luar dan lembut di dalam, berasal dari Prancis. Biasanya berbentuk setengah bulan dan sering disajikan sebagai sarapan.',
  ),
  Product(
    title: "Cookies",
    image: "assets/images/cookies.jpg",
    price: 12000,
    category: "Snack", 
    description: 'Cookies adalah kue kecil yang renyah di luar dan lembut di dalam, biasanya terbuat dari tepung, gula, mentega, dan bahan tambahan seperti cokelat chip atau kacang.',
  ),
  Product(
    title: "Donut",
    image: "assets/images/donut.jpg",
    price: 15000,
    category: "Snack",
    description: 'Donut adalah kue berbentuk cincin yang digoreng atau dipanggang, sering kali dilapisi gula, cokelat, atau glasir, dan bisa diisi dengan berbagai isian seperti krim atau selai.',
  ),
  Product(
    title: "Macaron",
    image: "assets/images/macaron.jpg",
    price: 20000,
    category: "Snack", 
    description: 'Macaron adalah kue kecil berbentuk bulat, terbuat dari meringue almond yang renyah di luar dan lembut di dalam, biasanya diisi dengan ganache, selai, atau krim.',
  ),
  Product(
    title: "Sandwich",
    image: "assets/images/sandwich.jpg",
    price: 25000,
    category: "Snack", 
    description: 'Sandwich adalah makanan yang terdiri dari dua potong roti yang diisi dengan bahan seperti daging, keju, sayuran, dan saus.',
  ),
  Product(
    title: "Muffin",
    image: "assets/images/muffin.jpg",
    price: 16000,
    category: "Snack", 
    description: 'Muffin adalah kue kecil yang lembut dan ringan, biasanya terbuat dari tepung, gula, telur, dan susu, dengan variasi rasa seperti cokelat, blueberry, atau pisang.',
  ),
  Product(
    title: "French Fries",
    image: "assets/images/frenchfries.jpg",
    price: 24000,
    category: "Snack", 
    description: 'French fries adalah kentang yang dipotong panjang dan digoreng hingga renyah, sering disajikan sebagai cemilan atau pendamping hidangan utama.',
  ),
  Product(
    title: "Onion Ring",
    image: "assets/images/onionring.jpg",
    price: 22000,
    category: "Snack", 
    description: 'Onion ring adalah irisan bawang yang dilapisi adonan tepung dan digoreng hingga renyah, sering disajikan sebagai cemilan atau pelengkap hidangan.',
  ),
];
